[package]
name = "poker-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
poker-core = { path = "../poker-core" }
rand = { workspace = true }
serde_json = { workspace = true }
eframe = { workspace = true }
egui_extras = { workspace = true }
env_logger = { workspace = true }
