[package]
name = "poker-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
