[package]
name = "poker-human"
version = "0.1.0"
edition = "2021"

[lib]
name = "poker_human"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "poker-human-cli"
path = "src/main.rs"

[dependencies]
poker-core = { path = "../../poker-core" }
poker-gui = { path = "../../poker-gui" }
pyo3 = { version = "0.25.0", features = ["auto-initialize"] }
rand = { workspace = true }
env_logger = { workspace = true }
eframe = { workspace = true }
egui_extras = { workspace = true }
