[package]
name = "gto-wizard-crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
poker-core = { path = "../poker-core" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["full"] }
thirtyfour = "0.35.0"
url = "2.5.4"
